# Generated by Django 4.1.7 on 2023-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='id_chat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
