# Generated by Django 4.1.7 on 2023-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dest',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='layout_img',
            name='dest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
