# Generated by Django 4.1.7 on 2023-04-05 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0002_alter_item_dest_alter_layout_img_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_layout',
            name='items_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_grapql.items_seller'),
        ),
        migrations.AlterField(
            model_name='page_layout',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_grapql.page'),
        ),
    ]
