# Generated by Django 4.1.7 on 2023-03-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0003_remove_chat_id_chat_supplier_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
