# Generated by Django 4.1.7 on 2023-03-18 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0004_seller_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryFileUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(upload_to='static/upload/fileupload/%Y/%m')),
                ('size', models.IntegerField()),
                ('typefile', models.TextField(blank=True, max_length=250, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
