# Generated by Django 4.1.7 on 2023-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0005_historyfileup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyfileup',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
