# Generated by Django 4.1.7 on 2023-03-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0006_alter_historyfileup_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_seller',
            name='price_sale',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='items_seller',
            name='price_sell',
            field=models.FloatField(default=0),
        ),
    ]
