# Generated by Django 4.1.7 on 2023-03-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0008_alter_invoice_item_item_likeitems_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_seller',
            name='promotion_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
