# Generated by Django 4.1.7 on 2023-03-19 11:24

import app_grapql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0009_items_seller_promotion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_seller',
            name='promotion_rate',
            field=models.FloatField(blank=True, default=0, null=True, validators=[app_grapql.models.validate_decimals]),
        ),
    ]
