# Generated by Django 4.1.7 on 2023-03-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0010_alter_items_seller_promotion_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_item',
            old_name='total_price',
            new_name='price',
        ),
    ]
