# Generated by Django 4.1.7 on 2023-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0011_rename_total_price_invoice_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status_now',
            field=models.CharField(choices=[(1, 'Addition'), (3, 'Deletion'), (4, 'Cancel'), (7, 'Complete')], default=1, max_length=50),
        ),
    ]
