# Generated by Django 4.1.7 on 2023-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0015_alter_invoice_item_number_alter_invoice_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeitems_seller',
            name='type',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'like'), (2, 'distlike')], default=0),
        ),
    ]
