# Generated by Django 4.1.7 on 2023-03-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0016_alter_likeitems_seller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_seller',
            name='stastus',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Internal', 'Internal'), ('Public', 'Public')], default='Public', max_length=250, null=True),
        ),
    ]
