# Generated by Django 4.1.7 on 2023-03-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0017_alter_items_seller_stastus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_seller',
            name='stastus',
            field=models.CharField(choices=[('Private', 'Private'), ('Internal', 'Internal'), ('Public', 'Public')], default='Public', max_length=250),
        ),
    ]
