# Generated by Django 4.1.7 on 2023-03-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0018_alter_items_seller_stastus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
