# Generated by Django 4.1.7 on 2023-03-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0021_invoiceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status_now',
            field=models.IntegerField(choices=[(1, 'Addition'), (8, 'Order'), (9, 'Approve'), (5, 'Send'), (4, 'Cancel'), (3, 'Deletion'), (7, 'Complete')], default=1),
        ),
        migrations.AlterField(
            model_name='invoice_history',
            name='status',
            field=models.CharField(choices=[(1, 'Addition'), (8, 'Order'), (9, 'Approve'), (5, 'Send'), (4, 'Cancel'), (3, 'Deletion'), (7, 'Complete')], default='create', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='cause',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='fullname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
