# Generated by Django 4.1.7 on 2023-03-27 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0022_alter_invoice_status_now_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
