# Generated by Django 4.1.7 on 2023-03-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grapql', '0023_layout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='dest',
            field=models.TextField(default='', null=True),
        ),
    ]
